insert into symptoms (date, name, severity, description) values ('2020-07-23 20:16:57', 'Ethyl Alcohol', 1, 'Other ossification of muscle, left thigh');
insert into symptoms (date, name, severity, description) values ('2020-10-15 16:26:05', 'RUMEX CRISPUS ROOT', 2, 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thG');
insert into symptoms (date, name, severity, description) values ('2020-09-26 01:49:10', 'Triclosan', 3, 'Corrosion of second degree of right elbow, sequela');
insert into symptoms (date, name, severity, description) values ('2020-10-08 03:42:40', 'TIZANIDINE HYDROCHLORIDE', 5, 'Nondisplaced fracture of first metatarsal bone, right foot');
insert into symptoms (date, name, severity, description) values ('2020-08-29 04:07:28', 'Docetaxel', 4, 'Matern care for disproprtn d/t outlet contrctn of pelv, fts1');
insert into symptoms (date, name, severity, description) values ('2020-08-05 14:56:13', 'Flumazenil', 3, 'Malignant neoplasm of uvula');
insert into symptoms (date, name, severity, description) values ('2020-11-11 03:22:43', 'Zinc Oxide', 4, 'Toxic effect of cyanides');
insert into symptoms (date, name, severity, description) values ('2020-10-02 08:56:25', 'Ibuprofen', 1, 'Drown due to fall/jump fr burning fishing boat, subs');
insert into symptoms (date, name, severity, description) values ('2020-09-05 18:19:10', 'Eucalyptol, menthol, methyl salicylate, thymol', 5, 'Car driver injured in collision w SUV in traf, subs');
insert into symptoms (date, name, severity, description) values ('2020-09-04 17:48:32', 'Dexbrompheniramine Maleate, Pseudoephedrine HCl', 1, 'Crushing injury of left ring finger, initial encounter');
insert into symptoms (date, name, severity, description) values ('2020-11-06 14:27:37', 'Chelidonium Majus, Echinacea, Glandula Suprarenalis Bovinum, Spleen, Carduus Marianus, Lycopodium Clavatum', 5, 'Disorders of magnesium metabolism, unspecified');
insert into symptoms (date, name, severity, description) values ('2020-09-16 19:32:39', 'Hydroxyzine Pamoate', 1, 'Lac w/o fb of abd wall, unsp q w penet perit cav, init');
insert into symptoms (date, name, severity, description) values ('2020-08-30 05:46:14', 'levocetirizine dihydrochloride', 3, 'Febrile convulsions');
insert into symptoms (date, name, severity, description) values ('2020-09-26 20:38:50', 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 1, 'Blister (nonthermal) of thigh');
insert into symptoms (date, name, severity, description) values ('2020-08-02 08:55:48', 'Alprostadil', 3, 'Prsn brd/alit pedl cyc injured in nonclsn trnsp acc, sequela');
insert into symptoms (date, name, severity, description) values ('2020-07-22 08:54:52', 'insulin-like growth factor-1 (IGF-1)', 1, 'Encounter for other contraceptive management');
insert into symptoms (date, name, severity, description) values ('2020-10-03 07:38:42', 'Cetirizine Hydrochloride', 4, 'Oth fx upr end l tibia, 7thE');
insert into symptoms (date, name, severity, description) values ('2020-11-07 03:17:36', 'OXYGEN', 4, 'Idiopathic gout, left shoulder');
insert into symptoms (date, name, severity, description) values ('2020-07-31 09:52:35', 'pegfilgrastim', 5, 'Other specified crystal arthropathies, hand');
insert into symptoms (date, name, severity, description) values ('2020-09-01 13:03:31', 'Paroxetine Hydrochloride', 5, 'Open bite of left lesser toe(s) w/o damage to nail, subs');
insert into symptoms (date, name, severity, description) values ('2020-09-22 01:39:15', 'nitroglycerin', 3, 'Poisoning by thrombolytic drug, self-harm, sequela');
insert into symptoms (date, name, severity, description) values ('2020-10-31 08:46:22', 'Octinoxate, Oxybenzone, Titanium Dioxide', 2, 'Nondisp fx of prox phalanx of l idx fngr, 7thP');
insert into symptoms (date, name, severity, description) values ('2020-10-18 22:48:53', 'DOXAPRAM HYDROCHLORIDE', 3, 'Sprain of unspecified ligament of right ankle, subs encntr');
insert into symptoms (date, name, severity, description) values ('2020-11-03 18:28:47', 'Oxymetazoline HCl', 4, 'Hypervitaminosis D');
insert into symptoms (date, name, severity, description) values ('2020-09-08 13:53:51', 'MENTHOL', 2, 'Displ seg fx shaft of r tibia, subs for clos fx w routn heal');
insert into symptoms (date, name, severity, description) values ('2020-09-27 04:09:46', 'TRAMETES VERSICOLOR FRUITING BODY', 5, 'Unsp injury of flexor musc/fasc/tend at forearm level');
insert into symptoms (date, name, severity, description) values ('2020-07-27 23:21:05', 'Atomoxetine hydrochloride', 2, 'Prsn brd/alit pedl cyc injured in clsn w 2/3-whl mv, sequela');
insert into symptoms (date, name, severity, description) values ('2020-11-08 02:55:40', 'CALENDULA OFFICINALIS FLOWER, SAMBUCUS NIGRA FLOWER, ECHINACEA ANGUSTIFOLIA, THUJA OCCIDENTALIS', 5, 'Displ spiral fx shaft of unsp fibula, 7thN');
insert into symptoms (date, name, severity, description) values ('2020-07-20 15:49:07', 'Alcohol', 4, 'Unspecified intracapsular fracture of right femur, sequela');
insert into symptoms (date, name, severity, description) values ('2020-11-02 03:26:11', 'ALCOHOL', 2, 'Contusion of left thumb without damage to nail, init encntr');
insert into symptoms (date, name, severity, description) values ('2020-08-31 17:36:52', 'prazosin hydrochloride', 4, 'Unsp foreign body in pharynx causing asphyxiation, init');
insert into symptoms (date, name, severity, description) values ('2020-10-29 02:04:31', 'hydrocodone bitartrate and acetaminophen', 4, 'Corrosion of first degree of right thigh');
insert into symptoms (date, name, severity, description) values ('2020-10-23 19:57:15', 'Phenol', 1, 'Displaced commnt fx unsp patella, init for opn fx type I/2');
insert into symptoms (date, name, severity, description) values ('2020-09-01 03:13:22', 'Aluminum Sesquichlorohydrate', 2, 'Blister (nonthermal), right lower leg, initial encounter');
insert into symptoms (date, name, severity, description) values ('2020-09-25 13:10:02', 'Sertraline Hydrochloride', 4, 'Pathological fracture in other disease, left tibia, sequela');
insert into symptoms (date, name, severity, description) values ('2020-10-22 16:04:08', 'Treatment Set TS349576', 3, 'Hydroxyapatite deposition disease, right hand');
insert into symptoms (date, name, severity, description) values ('2020-09-24 09:41:28', 'Anticoagulant Citrate Phosphate Dextrose Adenine', 3, 'Traum rupture of volar plate of finger at MCP/IP jt, subs');
insert into symptoms (date, name, severity, description) values ('2020-08-18 12:26:41', 'PYRITHIONE ZINC', 3, 'Dislocation of r acromioclav jt, > 200% displacmnt');
insert into symptoms (date, name, severity, description) values ('2020-10-15 09:29:02', 'ALCOHOL', 5, 'Other rheumatic mitral valve diseases');
insert into symptoms (date, name, severity, description) values ('2020-08-24 10:52:58', 'Acetaminophen', 4, 'Burn of unspecified internal organ, subsequent encounter');
insert into symptoms (date, name, severity, description) values ('2020-07-04 08:39:28', 'nabumetone', 1, 'Sciatica');
insert into symptoms (date, name, severity, description) values ('2020-09-09 19:14:39', 'SODIUM CHLORIDE', 3, 'Primary blast injury of lung, unspecified, sequela');
insert into symptoms (date, name, severity, description) values ('2020-08-13 12:02:03', 'olanzapine and fuoxetine', 3, 'Wedge comprsn fx fifth lum vertebra, subs for fx w nonunion');
insert into symptoms (date, name, severity, description) values ('2020-09-26 02:16:14', 'Trazodone Hydrochloride', 1, 'Contusion of unspecified part of pancreas, sequela');
insert into symptoms (date, name, severity, description) values ('2020-07-27 01:08:38', 'Alternaria alternata', 1, 'Burn of unspecified degree of chest wall');
insert into symptoms (date, name, severity, description) values ('2020-11-14 06:48:54', 'Modafinil', 3, 'Therapeutic gases');
insert into symptoms (date, name, severity, description) values ('2020-07-13 06:48:16', 'Ramipril', 2, 'Nondisp fx of shaft of first MC bone, unsp hand, sequela');
insert into symptoms (date, name, severity, description) values ('2020-07-20 23:57:58', 'Apis Mellifera 30X, Arsenic Trioxide 30X, Cinchona Officinalis Bark 30X, Digitalis 30X, Lachesis Muta Venom 30X, Lycopodium Clavatum Spore 30X, Sodium Sulfate 30X, Toxicodendron Pubescens Leaf 30X, Sambucus Nigra Flowering Top 30X, Strophanthus Hispidus Seed 30X', 5, 'Dislocation of proximal interphaln joint of left thumb, init');
insert into symptoms (date, name, severity, description) values ('2020-10-27 09:25:17', 'Bacitracin Zinc', 2, 'Unspecified fracture of head of left femur, sequela');
insert into symptoms (date, name, severity, description) values ('2020-08-16 19:27:45', 'Acetaminophen, Diphenhydramine Hydrochloride, Phenylephrine Hydrochloride', 5, 'Cont preg after spon abort of one fetus or more, first tri');